services:
  zk:
    image: ghcr.io/merlin-node/mote:latest
    container_name: mote-zk
    restart: unless-stopped
    ports:
      - "127.0.0.1:1888:25774"
    volumes:
      - ./data/config:/etc/zk
      - ./data/db:/var/lib/zk
    environment:
      - TZ=Asia/Shanghai
